In [3]:
import torch
torch.__version__

'2.7.1+cpu'

In [5]:
# Scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [ ]:
# dimensions of scalar
scalar.ndim

0

In [8]:
# get the item from the tensor as a python number
scalar.item()


5

In [11]:
scalar.shape

torch.Size([])

In [9]:
#vector
vector = torch.tensor([5,5,5])
vector

tensor([5, 5, 5])

In [10]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([3])

In [13]:
# Matrix
matrix = torch.tensor([[5,5,5],
                       [5,5,5],
                       [5,5,5]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([3, 3])

In [16]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6]]])

In [17]:
tensor.ndim

3

In [18]:
tensor.shape

torch.Size([1, 2, 3])

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1821, 0.3179, 0.2075, 0.3545],
        [0.3600, 0.8228, 0.1711, 0.0155],
        [0.4165, 0.5603, 0.0968, 0.9560]])

In [20]:
random_tensor.ndim

2

In [27]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
tensor.dtype

torch.int64

In [30]:
matrix.dtype

torch.int64

In [32]:
random_tensor.dtype

torch.float32

In [33]:
print(f"Device for tensor: {tensor.device}")

Device for tensor: cpu


In [50]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [4, 5],
                         [8, 9]], dtype=torch.float16)

tensor_B = torch.tensor([[11, 12],
                         [15, 16], 
                         [19, 20]], dtype=torch.float16)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [35]:
tensor_A * tensor_B

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])

In [37]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [38]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [39]:
tensor_A.shape

torch.Size([3, 2])

In [40]:
tensor_A.reshape(2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [51]:
tensor_A.dtype

torch.float16

In [54]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [55]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'